### PR TITLE
SQLite Database file

### PR DESCRIPTION
**Pull request by jenna-matthews**
Backup of sqlite database file - result of running the backup sql script.  Less than 25 records had an error and couldn't be created.

### CODE REVIEW

**Comment by jenna-matthews** [comment]
Adding a (zipped) backup of the sqlite database created by running the backup sql script.  Some records (< 25) failed to insert.  This will make it easier for others to load and review the data.

**Comment by jenna-matthews** [comment]
Several of the tables in this database are for baseball not hockey?

**Comment by rippinrobr** [comment]
I've some how combined the baseball and hockey dbs. Sorry about that. I get it fixed.

**Comment by jenna-matthews** [comment]
Thank you!

**Pull request closed without merging**
